# Generated by Django 4.2.2 on 2023-07-09 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0003_alter_message_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='Profile-Avatar.png', null=True, upload_to=''),
        ),
    ]
